### ISSUE TITLE
Error: While logging in

### ISSUE THREAD

**Issue by LuisSchuimer** [BytezoTeam/Eventfully#37]
Traceback (most recent call last):
  File "C:\Users\Benedikt\Documents\Eventfully\.venv\Lib\site-packages\flask\app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Benedikt\Documents\Eventfully\.venv\Lib\site-packages\flask\app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Benedikt\Documents\Eventfully\.venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Benedikt\Documents\Eventfully\.venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Benedikt\Documents\Eventfully\.venv\Lib\site-packages\flask\app.py", line 868, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Benedikt\Documents\Eventfully\.venv\Lib\site-packages\flask\app.py", line 1243, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Benedikt\Documents\Eventfully\.venv\Lib\site-packages\flask_wtf\csrf.py", line 229, in csrf_protect
    self.protect()
  File "C:\Users\Benedikt\Documents\Eventfully\.venv\Lib\site-packages\flask_wtf\csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "C:\Users\Benedikt\Documents\Eventfully\.venv\Lib\site-packages\flask_wtf\csrf.py", line 85, in validate_csrf
    secret_key = _get_config(
                 ^^^^^^^^^^^^
  File "C:\Users\Benedikt\Documents\Eventfully\.venv\Lib\site-packages\flask_wtf\csrf.py", line 136, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.

**Comment by 2mal3** [comment]
Gets fixed by #36, please review

**Comment by LuisSchuimer** [comment]
Please look at the comment on #36

**Comment by LuisSchuimer** [comment]
Fixed in #36
